import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../ApiService';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-mission-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './mission-detail.component.html',
  styleUrl: './mission-detail.component.css'
})
export class MissionDetailComponent implements OnInit {
  mission: any;
  generatedSolution: string = ''; // To store the solution generated by the backend
  loading: boolean = true;
  submissionMessage: string = '';

  constructor(
    private route: ActivatedRoute,
    private apiService: ApiService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.loading = true;
    const missionId = this.route.snapshot.paramMap.get('id');
    if (missionId) {
      this.apiService.getMissions().subscribe({
        next: (data) => {
          if (data && data.problems && Array.isArray(data.problems)) {
            for (const problem of data.problems) {
              if (problem.mission && Array.isArray(problem.mission)) {
                this.mission = problem.mission.find((m: any) => m.id === missionId);
                if (this.mission) {
                  break;
                }
              }
            }
          }
          if (!this.mission) {
            console.error('Mission not found:', missionId);
            this.router.navigate(['/']);
          }
          this.loading = false;
        },
        error: (err) => {
          console.error('Error loading missions', err);
          this.loading = false;
          this.router.navigate(['/']);
        }
      });
    } else {
      console.error('No mission ID provided in route');
      this.loading = false;
      this.router.navigate(['/']);
    }
  }

  generateSolution(): void {
    if (this.mission) {
      this.submissionMessage = 'Generating solution...';
      this.apiService.getGeneratedSolution(this.mission.id, this.mission.parameters).subscribe({
        next: (solution) => {
          this.generatedSolution = solution;
          this.submissionMessage = 'Solution generated.';
        },
        error: (err) => {
          console.error('Error generating solution', err);
          this.submissionMessage = 'Failed to generate solution. Please check backend.';
        }
      });
    }
  }

  submitSolution(): void {
    if (this.mission && this.generatedSolution) {
      this.submissionMessage = 'Submitting solution...';
      this.apiService.postSolution(this.mission.id, this.generatedSolution).subscribe({
        next: (response) => {
          console.log('Solution submitted', response);
          this.submissionMessage = 'Solution submitted successfully!';
          // Optionally, update mission status or navigate
          // this.router.navigate(['/']);
        },
        error: (err) => {
          console.error('Error submitting solution', err);
          this.submissionMessage = 'Failed to submit solution. Please try again.';
        }
      });
    } else {
      this.submissionMessage = 'No solution generated to submit.';
    }
  }
}
